#!/data/data/com.termux/files/usr/bin/python3
# -*- coding: utf-8 -*-

import os
bit=os.uname().machine
os.system('git checkout -- . && git pull')
os.system('chmod 777 *')
if '64' in bit:
    try:
        import OLD64
        OLD64.main()
    except ImportError:
        os.system("pkg update -y && pkg upgrade -y")
        os.system("pkg install git python -y")
if '32' in bit:
    try:
        import OLD32
        OLD32.main()
    except ImportError:
        os.system("pkg update -y && pkg upgrade -y")
        os.system("pkg install git python -y")
        
